contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram
        type: telegram
        settings:
          bot_token: ${TELEGRAM_BOT_TOKEN}
          chat_id: ${TELEGRAM_CHAT_ID}
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: telegram
    group_by:
      - alertname
      - instance
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h